from v02_pipeline import video,S,R,FIX,DEATH,FX
for name,run,death in [
 ('beetle','Loop a heavy tin beetle walking IN PLACE with alternating articulated legs, subtle shell rocking, exposed rear gear rotates. Same position, orientation and size, start and end match.','The armored tin beetle recoils, its teal dome shell pops off and tumbles sideways, brass plates separate, internal gears spill out and the little legs fold flat. Heavy chunks bounce and settle around original feet.'),
 ('jack','Loop a spring jack-in-the-box walking IN PLACE on its four tiny feet. The spring neck compresses and rebounds gently, wooden head nods with elastic secondary motion. Same baseline and orientation.','The spring clown compresses violently then its spring uncoils and falls limp sideways, the wooden head flops down, box lid drops and two wooden panels separate. Distinct spring and wood collapse with no gore.'),
 ('wasp','Loop a sewing-spool wasp hovering IN PLACE, two transparent wings beat rapidly with smooth motion blur, spool body gently bobs no more than 3 percent height, needle stinger stays consistent, no lateral travel.','The toy wasp wings snap off and flutter down, the thread-spool body loses lift and drops onto its side with a bounce, a short strand of thread unravels, needle falls nearby. All parts settle on the original foot baseline.'),
 ('boss','Loop a large toy scrap bulldozer driving IN PLACE. Tracks turn, the shovel rocks slightly from mechanical vibration, chimney gently trembles and cloth pennant flutters. No smoke, no translation, fixed camera.','The junk bulldozer shudders heavily, front shovel drops with a bounce, two track assemblies break away, cabin tilts and settles, big metal panels and winding key fall in a compact radius. A few tiny sparks allowed, no smoke hiding the wreck. All parts settle visibly.')]:
 ref=S/(name+'-ref.png')
 video(name+'_run',FIX+run,ref,loop=True)
 video(name+'_death',DEATH+death,ref,death=True)
for name,ref,desc in [
 ('battery_loop','battery','A beautiful small teal glass battery pickup slowly turns in place about its vertical axis, with internal teal liquid gently swirling and warm specular glints travelling around metal caps. One full gentle rotation in four seconds, position and scale unchanged, seamless loop, no added particles.'),
 ('medkit_loop','medkit','A rolled cream bandage and fluffy cotton bundle with teal thread slowly rocks and rotates gently in place, cloth surface compresses softly like breathing and the loose thread tip sways. Seamless loop, same position and scale, no added items.'),
 ('button_spin','button','A single thick teal sewing BUTTON with exactly four visible holes and raised worn rim spins smoothly in place like a tossed coin. Alternate the readable button face and its thick curved edge through two full rotations over four seconds, realistic changing highlights. Keep same center and scale. No trail, no extra objects, no transformation.')]:video(name,FIX+desc,S/(ref+'-ref.png'),loop=True)
video('doll_cast',FIX+'ONE attack: the jointed doll plants feet, pulls one arm back at .4 seconds, points and snaps arm sharply RIGHT at 1.0 seconds as if flicking a sewing pin, follows through then returns to the original pose by 2.3 seconds. No visible projectile, no glowing effects, preserve jointed limbs and original face.',R/'source/doll-video-reference-v1.png')
video('boss_slam',FIX+'ONE attack: the heavy bulldozer braces and raises its front shovel at .4 seconds, then slams the shovel down hard at 1.1 seconds, chassis compresses and rebounds, settles to original pose by 2.4 seconds. No movement across frame, no particles, no shockwave, no ground. Show clear anticipation and force.',S/'boss-ref.png')
video('pulse_ring',FX+'A thin expanding circular teal electric shockwave made of sharp sewing-thread lightning filaments. Bright small core pops once, ring expands outward smoothly with a few golden sparks, then dissipates, transparent gaps between filaments, keep center largely empty.')
video('crate_break',DEATH+'The open cardboard salvage crate crumples and bursts into five large torn cardboard panels with recognizable flaps, a few brass screws spill out, panels flutter down and settle flat. No particles obscuring the panels.',S/'prop_crate-ref.png',death=True)
